version: '2'
services:
  kafka-0:
    image: 'confluentinc/cp-kafka:7.6.1'
    networks:
      - streaming-network
    hostname: kafka_pipeline-0
    container_name: kafka_pipeline-0
    ports:
      - '9094:9094'
    volumes:
      - "kafka_data_0:/var/lib/kafka_pipeline/data"
      - "./kafka_pipeline/config/kafka_server_jaas.conf:/etc/kafka_pipeline/config/kafka_server_jaas.conf"
    environment:
      # KRaft settings
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka_pipeline-0:9093,1@kafka_pipeline-1:9093,2@kafka_pipeline-2:9093
      - CLUSTER_ID=XMVdmieVScezIPmnB_QcXA
      # Listeners
      - KAFKA_LISTENERS=CONTROLLER://:9093,INTERNAL://:29092,DOCKER_NETWORK://:9092,EXTERNAL://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka_pipeline-0:29092,DOCKER_NETWORK://kafka_pipeline-0:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,DOCKER_NETWORK:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # Clustering
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
#      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=3
#      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      # Server Default Properties
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_NUM_PARTITIONS=3
      # sasl
      - KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka_pipeline/config/kafka_server_jaas.conf
  kafka-1:
    image: 'confluentinc/cp-kafka:7.6.1'
    networks:
      - streaming-network
    hostname: kafka_pipeline-1
    container_name: kafka_pipeline-1
    ports:
      - '9194:9094'
    volumes:
      - "kafka_data_1:/var/lib/kafka_pipeline/data"
      - "./kafka_pipeline/config/kafka_server_jaas.conf:/etc/kafka_pipeline/config/kafka_server_jaas.conf"
    environment:
      # KRaft settings
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka_pipeline-0:9093,1@kafka_pipeline-1:9093,2@kafka_pipeline-2:9093
      - CLUSTER_ID=XMVdmieVScezIPmnB_QcXA
      # Listeners
      - KAFKA_LISTENERS=CONTROLLER://:9093,INTERNAL://:29092,DOCKER_NETWORK://:9092,EXTERNAL://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka_pipeline-1:29092,DOCKER_NETWORK://kafka_pipeline-1:9092,EXTERNAL://localhost:9194
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,DOCKER_NETWORK:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # Clustering
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
#      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      # Server Default Properties
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_NUM_PARTITIONS=3
      # sasl
      - KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka_pipeline/config/kafka_server_jaas.conf
  kafka-2:
    image: 'confluentinc/cp-kafka:7.6.1'
    networks:
      - streaming-network
    hostname: kafka_pipeline-2
    container_name: kafka_pipeline-2
    ports:
      - '9294:9094'
    volumes:
      - "kafka_data_2:/var/lib/kafka_pipeline/data"
      - "./kafka_pipeline/config/kafka_server_jaas.conf:/etc/kafka_pipeline/config/kafka_server_jaas.conf"
    environment:
      # KRaft settings
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka_pipeline-0:9093,1@kafka_pipeline-1:9093,2@kafka_pipeline-2:9093
      - CLUSTER_ID=XMVdmieVScezIPmnB_QcXA
      # Listeners
      - KAFKA_LISTENERS=CONTROLLER://:9093,INTERNAL://:29092,DOCKER_NETWORK://:9092,EXTERNAL://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka_pipeline-2:29092,DOCKER_NETWORK://kafka_pipeline-2:9092,EXTERNAL://localhost:9294
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,DOCKER_NETWORK:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # Clustering
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
#      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      # Server Default Properties
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_NUM_PARTITIONS=3
      # sasl
      - KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka_pipeline/config/kafka_server_jaas.conf
  akhq:
    image: 'tchiotludo/akhq:0.24.0'
    networks:
      - streaming-network
    container_name: akhq
    ports:
      - '8180:8080'
    environment:
      # echo -n "17022003" | shasum -a 256 (lệnh này để chuyển pass qua 256)
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-server:
              properties:
                bootstrap.servers: "kafka-0:9092,kafka-1:9092,kafka-2:9092"
                security.protocol: SASL_PLAINTEXT
                sasl.mechanism: PLAIN
                sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="17022003";
          security:
            default-group: no-roles
            basic-auth:
              - username: admin
                password: "a04a3f9e63224c033220ba0500be1e61bc44f8875d981b7622a5f2c23bff474d"
                passwordHash: SHA256
                groups:
                - admin
        micronaut:
            security:
              enabled: true
              token:
                jwt:
                  signatures:
                    secret:
                      generator:
                        secret: "a04a3f9e63224c033220ba0500be1e61bc44f8875d981b7622a5f2c23bff474d"

networks:
  streaming-network:
    external: true

volumes:
  kafka_data_0:
    driver: local
  kafka_data_1:
    driver: local
  kafka_data_2:
    driver: local